---
- hosts: all
  tasks:
    - name: ensure ntp is at the latest version
      apt: pkg=ntp state=latest update_cache=true
      notify:
      - restart ntpd
  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted
